// Generates frontend/js/firebase-config.js from .env (local) or environment variables (CI).
// Usage: npm run config
const fs = require('fs');
const path = require('path');

const envFile = path.join(__dirname, '..', '.env');
if (fs.existsSync(envFile)) {
  fs.readFileSync(envFile, 'utf8').split(/\r?\n/).forEach(line => {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  });
}
const e = process.env;
const cfg = {
  firebase: {
    apiKey: e.FIREBASE_API_KEY || '',
    authDomain: e.FIREBASE_AUTH_DOMAIN || '',
    projectId: e.FIREBASE_PROJECT_ID || '',
    appId: e.FIREBASE_APP_ID || '',
    messagingSenderId: e.FIREBASE_MESSAGING_SENDER_ID || ''
  },
  apiBaseUrl: e.WIR_API_BASE_URL || 'http://localhost:5000/api'
};
if (!cfg.firebase.apiKey || !cfg.firebase.projectId) {
  console.error('Missing FIREBASE_API_KEY / FIREBASE_PROJECT_ID (set them in .env or as environment variables).');
  process.exit(1);
}
fs.writeFileSync(path.join(__dirname, '..', 'frontend', 'js', 'firebase-config.js'),
  '// Generated by scripts/gen-config.js — public Firebase web config (not a secret).\nwindow.WIR_CONFIG = ' + JSON.stringify(cfg, null, 2) + ';\n');
console.log('Wrote frontend/js/firebase-config.js');
